version: '3.8'
volumes:
  pgdata:
services:
  postgresql:
    image: "bitnami/postgresql:16"
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: ppalli
