spring:
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://${PPALLI_DB_HOST}:${PPALLI_DB_PORT:5432}/${PPALLI_DB_NAME}"
    username: ${PPALLI_DB_USERNAME}
    password: ${PPALLI_DB_PASSWORD}
  liquibase:
    change-log: "classpath:/db/changelog/_main.yml"
    database-change-log-table: db_changelog
    database-change-log-lock-table: db_changelog_lock
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate

server:
  shutdown: graceful
  http2:
    enabled: true
  ssl:
    enabled: true
    certificate: ${PPALLI_CERT_PATH}
    certificate-private-key: ${PPALLI_CERT_KEY_PATH}
    trust-certificate: ${PPALLI_CA_PATH:}
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types:
      - text/html
      - text/xml
      - text/css
      - text/plain
      - application/javascript
      - application/json
      - application/xml
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    jsp:
      registered: false
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: warn
    ppalli: info
  charset:
    file: UTF-8
    console: UTF-8
  file:
    name: ./logs/ppalli.log
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-history: 30
      max-file-size: 10MB

