spring:
  devtools:
    add-properties: false
  docker:
    compose:
      lifecycle-management: start_only
  liquibase:
    drop-first: true
  jpa:
    show-sql: true

logging:
  level:
    root: info
    ppalli: debug
  file:
    name: "" # 로컬에서는 로그 파일을 남기지 않게
